package cn.ym.dao;

import cn.ym.pojo.Aproblem;
import cn.ym.pojo.AproblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AproblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int countByExample(AproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int deleteByExample(AproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int insert(Aproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int insertSelective(Aproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    List<Aproblem> selectByExample(AproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    Aproblem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Aproblem record, @Param("example") AproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int updateByExample(@Param("record") Aproblem record, @Param("example") AproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int updateByPrimaryKeySelective(Aproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    int updateByPrimaryKey(Aproblem record);
}