package cn.ym.dao;

import cn.ym.pojo.AssAprExample;
import cn.ym.pojo.AssAprKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssAprMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int countByExample(AssAprExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByExample(AssAprExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByPrimaryKey(AssAprKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insert(AssAprKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insertSelective(AssAprKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    List<AssAprKey> selectByExample(AssAprExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssAprKey record, @Param("example") AssAprExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ass_apr
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExample(@Param("record") AssAprKey record, @Param("example") AssAprExample example);
}