package cn.ym.dao;

import cn.ym.pojo.Filedoc;
import cn.ym.pojo.FiledocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiledocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int countByExample(FiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int deleteByExample(FiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int insert(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int insertSelective(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    List<Filedoc> selectByExample(FiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    Filedoc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") Filedoc record, @Param("example") FiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int updateByExample(@Param("record") Filedoc record, @Param("example") FiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int updateByPrimaryKeySelective(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    int updateByPrimaryKey(Filedoc record);
}