package cn.ym.dao;

import cn.ym.pojo.Questiontype;
import cn.ym.pojo.QuestiontypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestiontypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int countByExample(QuestiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByExample(QuestiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insert(Questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insertSelective(Questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    List<Questiontype> selectByExample(QuestiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    Questiontype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") Questiontype record, @Param("example") QuestiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExample(@Param("record") Questiontype record, @Param("example") QuestiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByPrimaryKeySelective(Questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByPrimaryKey(Questiontype record);
}