package cn.ym.dao;

import cn.ym.pojo.TeacherFiledocExample;
import cn.ym.pojo.TeacherFiledocKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherFiledocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int countByExample(TeacherFiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByExample(TeacherFiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int deleteByPrimaryKey(TeacherFiledocKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insert(TeacherFiledocKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int insertSelective(TeacherFiledocKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    List<TeacherFiledocKey> selectByExample(TeacherFiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") TeacherFiledocKey record, @Param("example") TeacherFiledocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    int updateByExample(@Param("record") TeacherFiledocKey record, @Param("example") TeacherFiledocExample example);
}