package cn.ym.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AproblemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public AproblemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNull() {
            addCriterion("Answer is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNotNull() {
            addCriterion("Answer is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerEqualTo(String value) {
            addCriterion("Answer =", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotEqualTo(String value) {
            addCriterion("Answer <>", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThan(String value) {
            addCriterion("Answer >", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("Answer >=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThan(String value) {
            addCriterion("Answer <", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThanOrEqualTo(String value) {
            addCriterion("Answer <=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLike(String value) {
            addCriterion("Answer like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotLike(String value) {
            addCriterion("Answer not like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerIn(List<String> values) {
            addCriterion("Answer in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotIn(List<String> values) {
            addCriterion("Answer not in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerBetween(String value1, String value2) {
            addCriterion("Answer between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotBetween(String value1, String value2) {
            addCriterion("Answer not between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andDottingIsNull() {
            addCriterion("Dotting is null");
            return (Criteria) this;
        }

        public Criteria andDottingIsNotNull() {
            addCriterion("Dotting is not null");
            return (Criteria) this;
        }

        public Criteria andDottingEqualTo(String value) {
            addCriterion("Dotting =", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingNotEqualTo(String value) {
            addCriterion("Dotting <>", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingGreaterThan(String value) {
            addCriterion("Dotting >", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingGreaterThanOrEqualTo(String value) {
            addCriterion("Dotting >=", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingLessThan(String value) {
            addCriterion("Dotting <", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingLessThanOrEqualTo(String value) {
            addCriterion("Dotting <=", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingLike(String value) {
            addCriterion("Dotting like", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingNotLike(String value) {
            addCriterion("Dotting not like", value, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingIn(List<String> values) {
            addCriterion("Dotting in", values, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingNotIn(List<String> values) {
            addCriterion("Dotting not in", values, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingBetween(String value1, String value2) {
            addCriterion("Dotting between", value1, value2, "dotting");
            return (Criteria) this;
        }

        public Criteria andDottingNotBetween(String value1, String value2) {
            addCriterion("Dotting not between", value1, value2, "dotting");
            return (Criteria) this;
        }

        public Criteria andAnalysisIsNull() {
            addCriterion("analysis is null");
            return (Criteria) this;
        }

        public Criteria andAnalysisIsNotNull() {
            addCriterion("analysis is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysisEqualTo(String value) {
            addCriterion("analysis =", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisNotEqualTo(String value) {
            addCriterion("analysis <>", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisGreaterThan(String value) {
            addCriterion("analysis >", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisGreaterThanOrEqualTo(String value) {
            addCriterion("analysis >=", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisLessThan(String value) {
            addCriterion("analysis <", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisLessThanOrEqualTo(String value) {
            addCriterion("analysis <=", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisLike(String value) {
            addCriterion("analysis like", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisNotLike(String value) {
            addCriterion("analysis not like", value, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisIn(List<String> values) {
            addCriterion("analysis in", values, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisNotIn(List<String> values) {
            addCriterion("analysis not in", values, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisBetween(String value1, String value2) {
            addCriterion("analysis between", value1, value2, "analysis");
            return (Criteria) this;
        }

        public Criteria andAnalysisNotBetween(String value1, String value2) {
            addCriterion("analysis not between", value1, value2, "analysis");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(String value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(String value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(String value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(String value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(String value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(String value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLike(String value) {
            addCriterion("body like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotLike(String value) {
            addCriterion("body not like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<String> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<String> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(String value1, String value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(String value1, String value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFiledocIdIsNull() {
            addCriterion("fileDoc_id is null");
            return (Criteria) this;
        }

        public Criteria andFiledocIdIsNotNull() {
            addCriterion("fileDoc_id is not null");
            return (Criteria) this;
        }

        public Criteria andFiledocIdEqualTo(Integer value) {
            addCriterion("fileDoc_id =", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdNotEqualTo(Integer value) {
            addCriterion("fileDoc_id <>", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdGreaterThan(Integer value) {
            addCriterion("fileDoc_id >", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fileDoc_id >=", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdLessThan(Integer value) {
            addCriterion("fileDoc_id <", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdLessThanOrEqualTo(Integer value) {
            addCriterion("fileDoc_id <=", value, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdIn(List<Integer> values) {
            addCriterion("fileDoc_id in", values, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdNotIn(List<Integer> values) {
            addCriterion("fileDoc_id not in", values, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdBetween(Integer value1, Integer value2) {
            addCriterion("fileDoc_id between", value1, value2, "filedocId");
            return (Criteria) this;
        }

        public Criteria andFiledocIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fileDoc_id not between", value1, value2, "filedocId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdIsNull() {
            addCriterion("questiontype_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdIsNotNull() {
            addCriterion("questiontype_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdEqualTo(Integer value) {
            addCriterion("questiontype_id =", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdNotEqualTo(Integer value) {
            addCriterion("questiontype_id <>", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdGreaterThan(Integer value) {
            addCriterion("questiontype_id >", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("questiontype_id >=", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdLessThan(Integer value) {
            addCriterion("questiontype_id <", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("questiontype_id <=", value, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdIn(List<Integer> values) {
            addCriterion("questiontype_id in", values, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdNotIn(List<Integer> values) {
            addCriterion("questiontype_id not in", values, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdBetween(Integer value1, Integer value2) {
            addCriterion("questiontype_id between", value1, value2, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andQuestiontypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("questiontype_id not between", value1, value2, "questiontypeId");
            return (Criteria) this;
        }

        public Criteria andZjIsNull() {
            addCriterion("zj is null");
            return (Criteria) this;
        }

        public Criteria andZjIsNotNull() {
            addCriterion("zj is not null");
            return (Criteria) this;
        }

        public Criteria andZjEqualTo(Integer value) {
            addCriterion("zj =", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjNotEqualTo(Integer value) {
            addCriterion("zj <>", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjGreaterThan(Integer value) {
            addCriterion("zj >", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjGreaterThanOrEqualTo(Integer value) {
            addCriterion("zj >=", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjLessThan(Integer value) {
            addCriterion("zj <", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjLessThanOrEqualTo(Integer value) {
            addCriterion("zj <=", value, "zj");
            return (Criteria) this;
        }

        public Criteria andZjIn(List<Integer> values) {
            addCriterion("zj in", values, "zj");
            return (Criteria) this;
        }

        public Criteria andZjNotIn(List<Integer> values) {
            addCriterion("zj not in", values, "zj");
            return (Criteria) this;
        }

        public Criteria andZjBetween(Integer value1, Integer value2) {
            addCriterion("zj between", value1, value2, "zj");
            return (Criteria) this;
        }

        public Criteria andZjNotBetween(Integer value1, Integer value2) {
            addCriterion("zj not between", value1, value2, "zj");
            return (Criteria) this;
        }

        public Criteria andZsdIsNull() {
            addCriterion("zsd is null");
            return (Criteria) this;
        }

        public Criteria andZsdIsNotNull() {
            addCriterion("zsd is not null");
            return (Criteria) this;
        }

        public Criteria andZsdEqualTo(Integer value) {
            addCriterion("zsd =", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdNotEqualTo(Integer value) {
            addCriterion("zsd <>", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdGreaterThan(Integer value) {
            addCriterion("zsd >", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdGreaterThanOrEqualTo(Integer value) {
            addCriterion("zsd >=", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdLessThan(Integer value) {
            addCriterion("zsd <", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdLessThanOrEqualTo(Integer value) {
            addCriterion("zsd <=", value, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdIn(List<Integer> values) {
            addCriterion("zsd in", values, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdNotIn(List<Integer> values) {
            addCriterion("zsd not in", values, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdBetween(Integer value1, Integer value2) {
            addCriterion("zsd between", value1, value2, "zsd");
            return (Criteria) this;
        }

        public Criteria andZsdNotBetween(Integer value1, Integer value2) {
            addCriterion("zsd not between", value1, value2, "zsd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aproblem
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 20 12:46:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aproblem
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}