package cn.ym.pojo;

import java.util.Date;

public class Aproblem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private String dotting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private String analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.date
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.status
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.fileDoc_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer filedocId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.questiontype_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer questiontypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.zj
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer zj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.zsd
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    private Integer zsd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.id
     *
     * @return the value of aproblem.id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.id
     *
     * @param id the value for aproblem.id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.Answer
     *
     * @return the value of aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.Answer
     *
     * @param answer the value for aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.Dotting
     *
     * @return the value of aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public String getDotting() {
        return dotting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.Dotting
     *
     * @param dotting the value for aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setDotting(String dotting) {
        this.dotting = dotting == null ? null : dotting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.analysis
     *
     * @return the value of aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.analysis
     *
     * @param analysis the value for aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.body
     *
     * @return the value of aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.body
     *
     * @param body the value for aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.date
     *
     * @return the value of aproblem.date
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.date
     *
     * @param date the value for aproblem.date
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.status
     *
     * @return the value of aproblem.status
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.status
     *
     * @param status the value for aproblem.status
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.fileDoc_id
     *
     * @return the value of aproblem.fileDoc_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getFiledocId() {
        return filedocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.fileDoc_id
     *
     * @param filedocId the value for aproblem.fileDoc_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setFiledocId(Integer filedocId) {
        this.filedocId = filedocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.questiontype_id
     *
     * @return the value of aproblem.questiontype_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getQuestiontypeId() {
        return questiontypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.questiontype_id
     *
     * @param questiontypeId the value for aproblem.questiontype_id
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setQuestiontypeId(Integer questiontypeId) {
        this.questiontypeId = questiontypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.zj
     *
     * @return the value of aproblem.zj
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getZj() {
        return zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.zj
     *
     * @param zj the value for aproblem.zj
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setZj(Integer zj) {
        this.zj = zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.zsd
     *
     * @return the value of aproblem.zsd
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public Integer getZsd() {
        return zsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.zsd
     *
     * @param zsd the value for aproblem.zsd
     *
     * @mbggenerated Thu Dec 20 12:46:32 CST 2018
     */
    public void setZsd(Integer zsd) {
        this.zsd = zsd;
    }
}