package cn.ym.pojo;

public class AproblemWithBLOBs extends Aproblem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    private String dotting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    private String analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.Answer
     *
     * @return the value of aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.Answer
     *
     * @param answer the value for aproblem.Answer
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.Dotting
     *
     * @return the value of aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public String getDotting() {
        return dotting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.Dotting
     *
     * @param dotting the value for aproblem.Dotting
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public void setDotting(String dotting) {
        this.dotting = dotting == null ? null : dotting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.analysis
     *
     * @return the value of aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.analysis
     *
     * @param analysis the value for aproblem.analysis
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aproblem.body
     *
     * @return the value of aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aproblem.body
     *
     * @param body the value for aproblem.body
     *
     * @mbggenerated Thu Dec 20 12:40:27 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }
}