package cn.ym.pojo;

public class AssAprKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ass_apr.pid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ass_apr.aid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer aid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ass_apr.pid
     *
     * @return the value of ass_apr.pid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ass_apr.pid
     *
     * @param pid the value for ass_apr.pid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ass_apr.aid
     *
     * @return the value of ass_apr.aid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ass_apr.aid
     *
     * @param aid the value for ass_apr.aid
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }
}