package cn.ym.pojo;

import java.util.ArrayList;
import java.util.List;

public class Assortment {
private	List<Assortment> list=new ArrayList<>();

public List<Assortment> getList() {
	return list;
}

public void setList(List<Assortment> list) {
	this.list = list;
}

	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.id
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.NodeCode
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private String nodecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.IsVisible
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private String isvisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.NodeName
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private String nodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.parentId
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.NodeOrder
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer nodeorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.NodeLevel
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer nodelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.Count
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.IsHaveChild
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private String ishavechild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assortment.status
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.id
     *
     * @return the value of assortment.id
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.id
     *
     * @param id the value for assortment.id
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.NodeCode
     *
     * @return the value of assortment.NodeCode
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public String getNodecode() {
        return nodecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.NodeCode
     *
     * @param nodecode the value for assortment.NodeCode
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setNodecode(String nodecode) {
        this.nodecode = nodecode == null ? null : nodecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.IsVisible
     *
     * @return the value of assortment.IsVisible
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public String getIsvisible() {
        return isvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.IsVisible
     *
     * @param isvisible the value for assortment.IsVisible
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setIsvisible(String isvisible) {
        this.isvisible = isvisible == null ? null : isvisible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.NodeName
     *
     * @return the value of assortment.NodeName
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.NodeName
     *
     * @param nodename the value for assortment.NodeName
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.parentId
     *
     * @return the value of assortment.parentId
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.parentId
     *
     * @param parentid the value for assortment.parentId
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.NodeOrder
     *
     * @return the value of assortment.NodeOrder
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getNodeorder() {
        return nodeorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.NodeOrder
     *
     * @param nodeorder the value for assortment.NodeOrder
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setNodeorder(Integer nodeorder) {
        this.nodeorder = nodeorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.NodeLevel
     *
     * @return the value of assortment.NodeLevel
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getNodelevel() {
        return nodelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.NodeLevel
     *
     * @param nodelevel the value for assortment.NodeLevel
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setNodelevel(Integer nodelevel) {
        this.nodelevel = nodelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.Count
     *
     * @return the value of assortment.Count
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.Count
     *
     * @param count the value for assortment.Count
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.IsHaveChild
     *
     * @return the value of assortment.IsHaveChild
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public String getIshavechild() {
        return ishavechild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.IsHaveChild
     *
     * @param ishavechild the value for assortment.IsHaveChild
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setIshavechild(String ishavechild) {
        this.ishavechild = ishavechild == null ? null : ishavechild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assortment.status
     *
     * @return the value of assortment.status
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assortment.status
     *
     * @param status the value for assortment.status
     *
     * @mbggenerated Sat Dec 22 15:26:15 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}