package cn.ym.pojo;

public class Common {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.path
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.status
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.shool
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String shool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.time
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common.trs
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String trs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.id
     *
     * @return the value of common.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.id
     *
     * @param id the value for common.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.name
     *
     * @return the value of common.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.name
     *
     * @param name the value for common.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.path
     *
     * @return the value of common.path
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.path
     *
     * @param path the value for common.path
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.status
     *
     * @return the value of common.status
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.status
     *
     * @param status the value for common.status
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.shool
     *
     * @return the value of common.shool
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getShool() {
        return shool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.shool
     *
     * @param shool the value for common.shool
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setShool(String shool) {
        this.shool = shool == null ? null : shool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.time
     *
     * @return the value of common.time
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.time
     *
     * @param time the value for common.time
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common.trs
     *
     * @return the value of common.trs
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getTrs() {
        return trs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common.trs
     *
     * @param trs the value for common.trs
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setTrs(String trs) {
        this.trs = trs == null ? null : trs.trim();
    }
}