package cn.ym.pojo;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.handleId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer handleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.handleName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String handlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.result
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.body
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.id
     *
     * @return the value of feedback.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.id
     *
     * @param id the value for feedback.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.handleId
     *
     * @return the value of feedback.handleId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getHandleid() {
        return handleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.handleId
     *
     * @param handleid the value for feedback.handleId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setHandleid(Integer handleid) {
        this.handleid = handleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.handleName
     *
     * @return the value of feedback.handleName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getHandlename() {
        return handlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.handleName
     *
     * @param handlename the value for feedback.handleName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setHandlename(String handlename) {
        this.handlename = handlename == null ? null : handlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.result
     *
     * @return the value of feedback.result
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.result
     *
     * @param result the value for feedback.result
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.teacher_id
     *
     * @return the value of feedback.teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.teacher_id
     *
     * @param teacherId the value for feedback.teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.body
     *
     * @return the value of feedback.body
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.body
     *
     * @param body the value for feedback.body
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }
}