package cn.ym.pojo;

import java.util.Date;

public class Filedoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.filename
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.filepath
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.status
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.uploadInfo
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String uploadinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.uploadIp
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String uploadip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.uploadTime
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private Date uploadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.teacher_id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.body
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.id
     *
     * @return the value of filedoc.id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.id
     *
     * @param id the value for filedoc.id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.filename
     *
     * @return the value of filedoc.filename
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.filename
     *
     * @param filename the value for filedoc.filename
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.filepath
     *
     * @return the value of filedoc.filepath
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.filepath
     *
     * @param filepath the value for filedoc.filepath
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.status
     *
     * @return the value of filedoc.status
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.status
     *
     * @param status the value for filedoc.status
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.uploadInfo
     *
     * @return the value of filedoc.uploadInfo
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getUploadinfo() {
        return uploadinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.uploadInfo
     *
     * @param uploadinfo the value for filedoc.uploadInfo
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setUploadinfo(String uploadinfo) {
        this.uploadinfo = uploadinfo == null ? null : uploadinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.uploadIp
     *
     * @return the value of filedoc.uploadIp
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getUploadip() {
        return uploadip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.uploadIp
     *
     * @param uploadip the value for filedoc.uploadIp
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setUploadip(String uploadip) {
        this.uploadip = uploadip == null ? null : uploadip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.uploadTime
     *
     * @return the value of filedoc.uploadTime
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.uploadTime
     *
     * @param uploadtime the value for filedoc.uploadTime
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.teacher_id
     *
     * @return the value of filedoc.teacher_id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.teacher_id
     *
     * @param teacherId the value for filedoc.teacher_id
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.body
     *
     * @return the value of filedoc.body
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.body
     *
     * @param body the value for filedoc.body
     *
     * @mbggenerated Sat Dec 22 17:01:16 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }
}