package cn.ym.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.createTime
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentClass
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String studentclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentPwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String studentpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studnetName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String studnetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String yan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.createTime
     *
     * @return the value of student.createTime
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.createTime
     *
     * @param createtime the value for student.createTime
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentClass
     *
     * @return the value of student.studentClass
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getStudentclass() {
        return studentclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentClass
     *
     * @param studentclass the value for student.studentClass
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setStudentclass(String studentclass) {
        this.studentclass = studentclass == null ? null : studentclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentId
     *
     * @return the value of student.studentId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentId
     *
     * @param studentid the value for student.studentId
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentPwd
     *
     * @return the value of student.studentPwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getStudentpwd() {
        return studentpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentPwd
     *
     * @param studentpwd the value for student.studentPwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setStudentpwd(String studentpwd) {
        this.studentpwd = studentpwd == null ? null : studentpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studnetName
     *
     * @return the value of student.studnetName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getStudnetname() {
        return studnetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studnetName
     *
     * @param studnetname the value for student.studnetName
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setStudnetname(String studnetname) {
        this.studnetname = studnetname == null ? null : studnetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.yan
     *
     * @return the value of student.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getYan() {
        return yan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.yan
     *
     * @param yan the value for student.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setYan(String yan) {
        this.yan = yan == null ? null : yan.trim();
    }
}