package cn.ym.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andSchoolIsNull() {
            addCriterion("school is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIsNotNull() {
            addCriterion("school is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolEqualTo(String value) {
            addCriterion("school =", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolNotEqualTo(String value) {
            addCriterion("school <>", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolGreaterThan(String value) {
            addCriterion("school >", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("school >=", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolLessThan(String value) {
            addCriterion("school <", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolLessThanOrEqualTo(String value) {
            addCriterion("school <=", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolLike(String value) {
            addCriterion("school like", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolNotLike(String value) {
            addCriterion("school not like", value, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolIn(List<String> values) {
            addCriterion("school in", values, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolNotIn(List<String> values) {
            addCriterion("school not in", values, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolBetween(String value1, String value2) {
            addCriterion("school between", value1, value2, "school");
            return (Criteria) this;
        }

        public Criteria andSchoolNotBetween(String value1, String value2) {
            addCriterion("school not between", value1, value2, "school");
            return (Criteria) this;
        }

        public Criteria andStudentclassIsNull() {
            addCriterion("studentClass is null");
            return (Criteria) this;
        }

        public Criteria andStudentclassIsNotNull() {
            addCriterion("studentClass is not null");
            return (Criteria) this;
        }

        public Criteria andStudentclassEqualTo(String value) {
            addCriterion("studentClass =", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassNotEqualTo(String value) {
            addCriterion("studentClass <>", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassGreaterThan(String value) {
            addCriterion("studentClass >", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassGreaterThanOrEqualTo(String value) {
            addCriterion("studentClass >=", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassLessThan(String value) {
            addCriterion("studentClass <", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassLessThanOrEqualTo(String value) {
            addCriterion("studentClass <=", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassLike(String value) {
            addCriterion("studentClass like", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassNotLike(String value) {
            addCriterion("studentClass not like", value, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassIn(List<String> values) {
            addCriterion("studentClass in", values, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassNotIn(List<String> values) {
            addCriterion("studentClass not in", values, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassBetween(String value1, String value2) {
            addCriterion("studentClass between", value1, value2, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentclassNotBetween(String value1, String value2) {
            addCriterion("studentClass not between", value1, value2, "studentclass");
            return (Criteria) this;
        }

        public Criteria andStudentidIsNull() {
            addCriterion("studentId is null");
            return (Criteria) this;
        }

        public Criteria andStudentidIsNotNull() {
            addCriterion("studentId is not null");
            return (Criteria) this;
        }

        public Criteria andStudentidEqualTo(String value) {
            addCriterion("studentId =", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidNotEqualTo(String value) {
            addCriterion("studentId <>", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidGreaterThan(String value) {
            addCriterion("studentId >", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidGreaterThanOrEqualTo(String value) {
            addCriterion("studentId >=", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidLessThan(String value) {
            addCriterion("studentId <", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidLessThanOrEqualTo(String value) {
            addCriterion("studentId <=", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidLike(String value) {
            addCriterion("studentId like", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidNotLike(String value) {
            addCriterion("studentId not like", value, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidIn(List<String> values) {
            addCriterion("studentId in", values, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidNotIn(List<String> values) {
            addCriterion("studentId not in", values, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidBetween(String value1, String value2) {
            addCriterion("studentId between", value1, value2, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentidNotBetween(String value1, String value2) {
            addCriterion("studentId not between", value1, value2, "studentid");
            return (Criteria) this;
        }

        public Criteria andStudentpwdIsNull() {
            addCriterion("studentPwd is null");
            return (Criteria) this;
        }

        public Criteria andStudentpwdIsNotNull() {
            addCriterion("studentPwd is not null");
            return (Criteria) this;
        }

        public Criteria andStudentpwdEqualTo(String value) {
            addCriterion("studentPwd =", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdNotEqualTo(String value) {
            addCriterion("studentPwd <>", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdGreaterThan(String value) {
            addCriterion("studentPwd >", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdGreaterThanOrEqualTo(String value) {
            addCriterion("studentPwd >=", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdLessThan(String value) {
            addCriterion("studentPwd <", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdLessThanOrEqualTo(String value) {
            addCriterion("studentPwd <=", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdLike(String value) {
            addCriterion("studentPwd like", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdNotLike(String value) {
            addCriterion("studentPwd not like", value, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdIn(List<String> values) {
            addCriterion("studentPwd in", values, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdNotIn(List<String> values) {
            addCriterion("studentPwd not in", values, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdBetween(String value1, String value2) {
            addCriterion("studentPwd between", value1, value2, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudentpwdNotBetween(String value1, String value2) {
            addCriterion("studentPwd not between", value1, value2, "studentpwd");
            return (Criteria) this;
        }

        public Criteria andStudnetnameIsNull() {
            addCriterion("studnetName is null");
            return (Criteria) this;
        }

        public Criteria andStudnetnameIsNotNull() {
            addCriterion("studnetName is not null");
            return (Criteria) this;
        }

        public Criteria andStudnetnameEqualTo(String value) {
            addCriterion("studnetName =", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameNotEqualTo(String value) {
            addCriterion("studnetName <>", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameGreaterThan(String value) {
            addCriterion("studnetName >", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameGreaterThanOrEqualTo(String value) {
            addCriterion("studnetName >=", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameLessThan(String value) {
            addCriterion("studnetName <", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameLessThanOrEqualTo(String value) {
            addCriterion("studnetName <=", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameLike(String value) {
            addCriterion("studnetName like", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameNotLike(String value) {
            addCriterion("studnetName not like", value, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameIn(List<String> values) {
            addCriterion("studnetName in", values, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameNotIn(List<String> values) {
            addCriterion("studnetName not in", values, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameBetween(String value1, String value2) {
            addCriterion("studnetName between", value1, value2, "studnetname");
            return (Criteria) this;
        }

        public Criteria andStudnetnameNotBetween(String value1, String value2) {
            addCriterion("studnetName not between", value1, value2, "studnetname");
            return (Criteria) this;
        }

        public Criteria andYanIsNull() {
            addCriterion("yan is null");
            return (Criteria) this;
        }

        public Criteria andYanIsNotNull() {
            addCriterion("yan is not null");
            return (Criteria) this;
        }

        public Criteria andYanEqualTo(String value) {
            addCriterion("yan =", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotEqualTo(String value) {
            addCriterion("yan <>", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanGreaterThan(String value) {
            addCriterion("yan >", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanGreaterThanOrEqualTo(String value) {
            addCriterion("yan >=", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLessThan(String value) {
            addCriterion("yan <", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLessThanOrEqualTo(String value) {
            addCriterion("yan <=", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLike(String value) {
            addCriterion("yan like", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotLike(String value) {
            addCriterion("yan not like", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanIn(List<String> values) {
            addCriterion("yan in", values, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotIn(List<String> values) {
            addCriterion("yan not in", values, "yan");
            return (Criteria) this;
        }

        public Criteria andYanBetween(String value1, String value2) {
            addCriterion("yan between", value1, value2, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotBetween(String value1, String value2) {
            addCriterion("yan not between", value1, value2, "yan");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}