package cn.ym.pojo;

import java.util.ArrayList;
import java.util.List;

public class TeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public TeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("img is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("img is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("img =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("img <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("img >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("img >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("img <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("img <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("img like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("img not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("img in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("img not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("img between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("img not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPostoneIsNull() {
            addCriterion("postOne is null");
            return (Criteria) this;
        }

        public Criteria andPostoneIsNotNull() {
            addCriterion("postOne is not null");
            return (Criteria) this;
        }

        public Criteria andPostoneEqualTo(String value) {
            addCriterion("postOne =", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneNotEqualTo(String value) {
            addCriterion("postOne <>", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneGreaterThan(String value) {
            addCriterion("postOne >", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneGreaterThanOrEqualTo(String value) {
            addCriterion("postOne >=", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneLessThan(String value) {
            addCriterion("postOne <", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneLessThanOrEqualTo(String value) {
            addCriterion("postOne <=", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneLike(String value) {
            addCriterion("postOne like", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneNotLike(String value) {
            addCriterion("postOne not like", value, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneIn(List<String> values) {
            addCriterion("postOne in", values, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneNotIn(List<String> values) {
            addCriterion("postOne not in", values, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneBetween(String value1, String value2) {
            addCriterion("postOne between", value1, value2, "postone");
            return (Criteria) this;
        }

        public Criteria andPostoneNotBetween(String value1, String value2) {
            addCriterion("postOne not between", value1, value2, "postone");
            return (Criteria) this;
        }

        public Criteria andPostthreeIsNull() {
            addCriterion("postThree is null");
            return (Criteria) this;
        }

        public Criteria andPostthreeIsNotNull() {
            addCriterion("postThree is not null");
            return (Criteria) this;
        }

        public Criteria andPostthreeEqualTo(String value) {
            addCriterion("postThree =", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeNotEqualTo(String value) {
            addCriterion("postThree <>", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeGreaterThan(String value) {
            addCriterion("postThree >", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeGreaterThanOrEqualTo(String value) {
            addCriterion("postThree >=", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeLessThan(String value) {
            addCriterion("postThree <", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeLessThanOrEqualTo(String value) {
            addCriterion("postThree <=", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeLike(String value) {
            addCriterion("postThree like", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeNotLike(String value) {
            addCriterion("postThree not like", value, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeIn(List<String> values) {
            addCriterion("postThree in", values, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeNotIn(List<String> values) {
            addCriterion("postThree not in", values, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeBetween(String value1, String value2) {
            addCriterion("postThree between", value1, value2, "postthree");
            return (Criteria) this;
        }

        public Criteria andPostthreeNotBetween(String value1, String value2) {
            addCriterion("postThree not between", value1, value2, "postthree");
            return (Criteria) this;
        }

        public Criteria andPosttowIsNull() {
            addCriterion("postTow is null");
            return (Criteria) this;
        }

        public Criteria andPosttowIsNotNull() {
            addCriterion("postTow is not null");
            return (Criteria) this;
        }

        public Criteria andPosttowEqualTo(String value) {
            addCriterion("postTow =", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowNotEqualTo(String value) {
            addCriterion("postTow <>", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowGreaterThan(String value) {
            addCriterion("postTow >", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowGreaterThanOrEqualTo(String value) {
            addCriterion("postTow >=", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowLessThan(String value) {
            addCriterion("postTow <", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowLessThanOrEqualTo(String value) {
            addCriterion("postTow <=", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowLike(String value) {
            addCriterion("postTow like", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowNotLike(String value) {
            addCriterion("postTow not like", value, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowIn(List<String> values) {
            addCriterion("postTow in", values, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowNotIn(List<String> values) {
            addCriterion("postTow not in", values, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowBetween(String value1, String value2) {
            addCriterion("postTow between", value1, value2, "posttow");
            return (Criteria) this;
        }

        public Criteria andPosttowNotBetween(String value1, String value2) {
            addCriterion("postTow not between", value1, value2, "posttow");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andYanIsNull() {
            addCriterion("yan is null");
            return (Criteria) this;
        }

        public Criteria andYanIsNotNull() {
            addCriterion("yan is not null");
            return (Criteria) this;
        }

        public Criteria andYanEqualTo(String value) {
            addCriterion("yan =", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotEqualTo(String value) {
            addCriterion("yan <>", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanGreaterThan(String value) {
            addCriterion("yan >", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanGreaterThanOrEqualTo(String value) {
            addCriterion("yan >=", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLessThan(String value) {
            addCriterion("yan <", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLessThanOrEqualTo(String value) {
            addCriterion("yan <=", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanLike(String value) {
            addCriterion("yan like", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotLike(String value) {
            addCriterion("yan not like", value, "yan");
            return (Criteria) this;
        }

        public Criteria andYanIn(List<String> values) {
            addCriterion("yan in", values, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotIn(List<String> values) {
            addCriterion("yan not in", values, "yan");
            return (Criteria) this;
        }

        public Criteria andYanBetween(String value1, String value2) {
            addCriterion("yan between", value1, value2, "yan");
            return (Criteria) this;
        }

        public Criteria andYanNotBetween(String value1, String value2) {
            addCriterion("yan not between", value1, value2, "yan");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}