package cn.ym.pojo;

import java.util.ArrayList;
import java.util.List;

public class TeacherFiledocExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public TeacherFiledocExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("Teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("Teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(Integer value) {
            addCriterion("Teacher_id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(Integer value) {
            addCriterion("Teacher_id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(Integer value) {
            addCriterion("Teacher_id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Teacher_id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(Integer value) {
            addCriterion("Teacher_id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(Integer value) {
            addCriterion("Teacher_id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<Integer> values) {
            addCriterion("Teacher_id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<Integer> values) {
            addCriterion("Teacher_id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(Integer value1, Integer value2) {
            addCriterion("Teacher_id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Teacher_id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdIsNull() {
            addCriterion("fileDocs_id is null");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdIsNotNull() {
            addCriterion("fileDocs_id is not null");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdEqualTo(Integer value) {
            addCriterion("fileDocs_id =", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdNotEqualTo(Integer value) {
            addCriterion("fileDocs_id <>", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdGreaterThan(Integer value) {
            addCriterion("fileDocs_id >", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fileDocs_id >=", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdLessThan(Integer value) {
            addCriterion("fileDocs_id <", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdLessThanOrEqualTo(Integer value) {
            addCriterion("fileDocs_id <=", value, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdIn(List<Integer> values) {
            addCriterion("fileDocs_id in", values, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdNotIn(List<Integer> values) {
            addCriterion("fileDocs_id not in", values, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdBetween(Integer value1, Integer value2) {
            addCriterion("fileDocs_id between", value1, value2, "filedocsId");
            return (Criteria) this;
        }

        public Criteria andFiledocsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fileDocs_id not between", value1, value2, "filedocsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_filedoc
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_filedoc
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}