package cn.ym.pojo;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.email
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.img
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.phone
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.postOne
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String postone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.postThree
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String postthree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.postTow
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String posttow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.pwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private String yan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.email
     *
     * @return the value of teacher.email
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.email
     *
     * @param email the value for teacher.email
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.img
     *
     * @return the value of teacher.img
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.img
     *
     * @param img the value for teacher.img
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.postOne
     *
     * @return the value of teacher.postOne
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPostone() {
        return postone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.postOne
     *
     * @param postone the value for teacher.postOne
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPostone(String postone) {
        this.postone = postone == null ? null : postone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.postThree
     *
     * @return the value of teacher.postThree
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPostthree() {
        return postthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.postThree
     *
     * @param postthree the value for teacher.postThree
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPostthree(String postthree) {
        this.postthree = postthree == null ? null : postthree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.postTow
     *
     * @return the value of teacher.postTow
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPosttow() {
        return posttow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.postTow
     *
     * @param posttow the value for teacher.postTow
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPosttow(String posttow) {
        this.posttow = posttow == null ? null : posttow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.pwd
     *
     * @return the value of teacher.pwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.pwd
     *
     * @param pwd the value for teacher.pwd
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.yan
     *
     * @return the value of teacher.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public String getYan() {
        return yan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.yan
     *
     * @param yan the value for teacher.yan
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setYan(String yan) {
        this.yan = yan == null ? null : yan.trim();
    }
}