package cn.ym.pojo;

public class TeacherFiledocKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_filedoc.Teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_filedoc.fileDocs_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    private Integer filedocsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_filedoc.Teacher_id
     *
     * @return the value of teacher_filedoc.Teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_filedoc.Teacher_id
     *
     * @param teacherId the value for teacher_filedoc.Teacher_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_filedoc.fileDocs_id
     *
     * @return the value of teacher_filedoc.fileDocs_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public Integer getFiledocsId() {
        return filedocsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_filedoc.fileDocs_id
     *
     * @param filedocsId the value for teacher_filedoc.fileDocs_id
     *
     * @mbggenerated Tue Dec 18 10:33:18 CST 2018
     */
    public void setFiledocsId(Integer filedocsId) {
        this.filedocsId = filedocsId;
    }
}